server:
  port: 8085
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: product-service
  datasource:
    password: ''
    url: jdbc:h2:mem:springboot
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
